### ISSUE TITLE
Migration to Maven

### ISSUE THREAD

**Issue by wetneb** [stkenny/grefine-rdf-extension#10]
Hi @stkenny,

OpenRefine now uses Maven instead of ant. So the upcoming release (3.1 probably) will require  extensions to use this build system too. I hope this is not going to be too much trouble to migrate - but I think you were already using maven for tests?

I have written a quick migration guide here:
https://github.com/OpenRefine/OpenRefine/wiki/Migration-guide-for-extension-and-fork-maintainers

The migration also mentions a migration from org.json to Jackson, but that is still in progress.

Let me know if you need any help for the migration. And thanks a lot for your work!

**Comment by wetneb** [comment]
I had a closer look at the setup and it seems that the extension is running fine in the current state - but there might be some inconsistencies in the dependencies that could show up only at run time.

Keeping the same build set up should be fine (because it does not actually rely on openrefine using Ant or Maven) but it might be preferable to migrate to the same Maven set up as the rest of the extensions.

In this case, it might make it easier for you if we publish the OpenRefine modules in Maven Central, so that you can get rid of your local repository altogether (that would also require uploading the other outstanding jars, which I want to get rid of anyway).

**Comment by stkenny** [comment]
Hi, I might be able to use jitpack now instead of having OpenRefine in the local repository. I'll try it out.

**Comment by wetneb** [comment]
I tried to run jitpack on the 3.1-beta release but it seems that it fails because the extra jars we provide don't get installed first: https://jitpack.io/com/github/OpenRefine/OpenRefine/3.1-beta/build.log

If there is anything we can do to our `pom.xml` files to make it work for you I would be happy to help.
