### ISSUE TITLE
RDF-Turtle Export Option Missing

### ISSUE THREAD

**Issue by kidehen** [stkenny/grefine-rdf-extension#17]
I have two RDF-XML export options rather than one for  RDF-XML and another for RDF-Turtle.

<img width="266" alt="screen shot 2018-12-18 at 10 07 51 am" src="https://user-images.githubusercontent.com/1541745/50162713-fb953180-02ac-11e9-9cf9-87ed2fab3aa3.png">

Is there a manual workaround for this issue?

**Comment by stkenny** [comment]
Wrong translation string in the menu option! The entry furthest down is the Turtle option, just incorrectly labelled.
