### ISSUE TITLE
Installation: mvn assembly:single

### ISSUE THREAD

**Issue by a-cohen** [stkenny/grefine-rdf-extension#19]
I ran into an error while attempting to install this extension. We were able to make it up to the `mvn assembly:single` step but got this error `[ERROR] Failed to execute goal on project grefine-rdf-extension: Could not resolve dependenci   es for project nl.dtls:grefine-rdf-extension:jar:1.1.0: Failure to find com.github.jsonld-jav   a.jsonld-java:jsonld-java:bundle:0.8.3 in https://dev-iesl.cs.umass.edu/nexus/content/reposit   ories/releases/ was cached in the local repository, resolution will not be reattempted until    the update interval of IESL UMass has elapsed or updates are forced` 

We followed https://dev-iesl.cs.umass.edu/nexus/content/repositories/releases/ to where the jsonld-java file should be, but it appears to no longer be there. 

Any assistance you could give on this issue would be greatly appreciated.

**Comment by stkenny** [comment]
Hi, that dependency is in the main Maven repository:
`Downloading: https://repo.maven.apache.org/maven2/com/github/jsonld-java/jsonld-java/0.8.3/jsonld-java-0.8.3.jar
Downloaded: https://repo.maven.apache.org/maven2/com/github/jsonld-java/jsonld-java/0.8.3/jsonld-java-0.8.3.jar (120 KB at 766.9 KB/sec)`

It should have been downloaded in the compile step as well. The build completed OK?

**Comment by phillip-mueller** [comment]
Hi,

I've encountered the exact same error. Unfortunately, for me it still doesn't resolve the dependency with your workaround. I also tried adding the bundle and dependency manually before without success. I just can't get my head around this problem. An update on this topic or another suggestion to resolve this issue would be highly appreciated. 

[debug_output.txt](https://github.com/stkenny/grefine-rdf-extension/files/2808754/debug_output.txt)

**Comment by stkenny** [comment]
Adding the jar to the project -repository worked for me. I'm trying to update other dependencies to remove the need for this jar version, but it's taking a while to figure out the various versions. I was only able to reproduce your error by deleting everything from ~/.m2.

**Comment by stkenny** [comment]
The dependency on jsonld has been removed by no longer using any23 to import prefixes.

**Comment by jurawrssic** [comment]
Hello, I'm getting the same error, even if I place the jsonld.jar file in project-repo it doesn't change the error message, could you spark some light please it doesn't compile at all and OpenRefine gives me the butterfly error

**Comment by stkenny** [comment]
Hi, jsonld is no longer a dependency so you should not be getting this error. What version of the code are you using? Can you post the butterfly error you are getting?
