### ISSUE TITLE
Default prefixes are not working

### ISSUE THREAD

**Issue by rajaram5** [stkenny/grefine-rdf-extension#21]
Hello,
In the `rdf skeleton` window the autocomplete is not working for default prefixes. I try to search for type Person excepting `foaf:Person` from the drop down option. But I didn't get any suggestions.

Regards,
Rajaram

**Comment by stkenny** [comment]
If you go to Manage by the Available Prefixes does pressing Refresh next to the vocabulary make it work again? Or if not, delete and re-add the prefix?
