### ISSUE TITLE
Multi value cells

### ISSUE THREAD

**Issue by EmidioStani** [stkenny/grefine-rdf-extension#22]
Hello,

maybe I am wrong but it seems when converting to RDF I cannot assign multiple values (a cell which contains multiple values separated by commas) to a property, even if I split the cell before.

Do you confirm ? And what would be a workaround ?

**Comment by stkenny** [comment]
Are you getting an error, or just not the output you expect? What is the expected output? You might need to split the cell value into multiple rows.

**Comment by EmidioStani** [comment]
Hello,
thanks for coming back to this.
It is mostly the output that I would not expect.
Imagine I have a simple CSV like:
test1,test2,"test3,test4,test5",test6
Then on column 3 I apply the split multi value cells
Then I click on "show as records" (so the values test3, test4 and test5 belong to the same record)
Then I map each column to a rdf property.
I would expect that the 3 properties belong to the same object (record) of column1 but they will part of different objects (record).

 <http://localhost:3333/0> a foaf:Agent ; dct:identifier "test1" ; dct:publisher "test2" ; dct:description "test3" ; dct:title "test6" .
<http://localhost:3333/1> a foaf:Agent ; dct:description "test4" .
<http://localhost:3333/2> a foaf:Agent ; dct:description "test5" 

While I would like to have:

 <http://localhost:3333/0> a foaf:Agent ; dct:identifier "test1" ; dct:publisher "test2" ; dct:description "test3" ; dct:title "test6" .
<http://localhost:3333/0> a foaf:Agent ; dct:description "test4" .
<http://localhost:3333/0> a foaf:Agent ; dct:description "test5" .

**Comment by EmidioStani** [comment]
Hi, I found out the way, just use the value.split(",") in the mapped column
