### ISSUE TITLE
Turtle export is working but wrongly labeled

### ISSUE THREAD

**Issue by ktk** [stkenny/grefine-rdf-extension#26]
On Mac and Linux where I tested I see this in the export tab:

<img width="285" alt="Screen Shot 2019-06-19 at 11 41 24" src="https://user-images.githubusercontent.com/583021/59754858-3d685a00-9287-11e9-94f8-17812bc2883d.png">

The first entry indeed returns RDF/XML, while the second one exports Turtle.

**Comment by stkenny** [comment]
Odd, that was fixed in this commit https://github.com/stkenny/grefine-rdf-extension/commit/58b8e26945c7743e55c9a6b28c48352a5c0f656f, which is in v1.1.1

![Screenshot from 2019-06-19 15-36-35](https://user-images.githubusercontent.com/1716730/59774915-2e45d400-92a8-11e9-8201-932ec36fbf80.png)

**Comment by ktk** [comment]
Ah sorry I did not update to 1.1.1. yet when I wrote that :) Thanks!
