### ISSUE TITLE
tests are not configured correctly in Maven

### ISSUE THREAD

**Issue by goudvisje** [stkenny/grefine-rdf-extension#3]
Hi StKenny,

Thanks for making the rdf-extension available for Maven. Liking it a lot! Everything was working in no-time, accept for the tests.

I'm writing to you, because I'm not managing to get the tests running with the current config.
![image](https://user-images.githubusercontent.com/9056360/43504883-419bb786-9565-11e8-8b30-c2162ef205f2.png)

Looks like the assembled OpenRefine zip is not visible for tests. Could you help me with how to fix this in pom.xml?

Cheers, Goudvisje

**Comment by stkenny** [comment]
Hi, the tests need to be updated and changed quite a bit to get them working again. I'm working on that at the moment. Thanks.

**Comment by goudvisje** [comment]
Holy moly.. I see you changed the whole namespace.. that is indeed some work. If you need some help, please shout
