### ISSUE TITLE
Do not change OpenRefine's default styles

### ISSUE THREAD

**Issue by MarekSuchanek** [stkenny/grefine-rdf-extension#36]
Your extension is affecting look of other extensions and OpenRefine itself. Please, change styles only under your classes or other identifiers if you really need to change the default style.

For example (but there are many more):

https://github.com/stkenny/grefine-rdf-extension/blob/2690d2c939b9f08f657658b78257b10f06e0fd7f/src/main/resources/module/styles/rdf-reconcile-service.css#L71-L80

**Comment by stkenny** [comment]
Fixed in 1.1.7 and 1.1.4
