### ISSUE TITLE
Edit RDF Skeleton not working

### ISSUE THREAD

**Issue by rogargon** [stkenny/grefine-rdf-extension#38]
Trying to edit the RDF Skeleton with OpenRefine 3.2 and the corresponding RDF Extension. When I click the "Preview edit" link:

![image](https://user-images.githubusercontent.com/1313870/72604392-19532100-391b-11ea-813b-2bea300c85dd.png)

There is a null pointer exception that breaks the preview and code editor popup:

![image](https://user-images.githubusercontent.com/1313870/72604902-11e04780-391c-11ea-9cb6-db0b7211903e.png)

Concretely, the error in the console is:

`project-bundle.js:42796 Uncaught TypeError: Cannot read property 'code' of null`

And corresponds to the following piece of code:

```
var cmdUrl = "command/rdf-extension/preview-rdf-expression?" ;
		$.post(
				cmdUrl + $.param(params), 
				{
					rowIndices: JSON.stringify(this._rowIndices) 
				},
				function(data) {
					if (data.code != "error") {
						self._results = data.results;
					} else {
						self._results = null;
					}
					self._renderPreview(expression, isRowNumberCell, data);
				},	
				"json"
		);
``` 

The corresponding call generated by this code is not returning any result and thus even the `data.code != "error"` check if failing because `data` is null.

**Comment by Gossann** [comment]
I have the same issue. Is there a different version where the preview is working?

**Comment by stkenny** [comment]
Hi, no I haven't had time to look at a fix yet. I'll try and get a new release done in the next day or so.

**Comment by stkenny** [comment]
Should now be fixed in https://github.com/stkenny/grefine-rdf-extension/releases/download/v1.1.8-orefine-3.2/rdf-extension-1.1.8-orefine-3.2.zip

**Comment by Gossann** [comment]
Thank you! It works.

**Comment by rogargon** [comment]
It seems to work perfectly now. Even tested with OpenRefine 3.3 without any perceivable issue for the moment. Great work @stkenny 👏
