### ISSUE TITLE
Adding new prefix from web doesn't work

### ISSUE THREAD

**Issue by ecamossi** [stkenny/grefine-rdf-extension#41]
Hello,

I'm using rdf-extension-1.2.0 with openrefine 3.3. I tried to add dbo prefix but the import from web seems blocked. OK is enabled but doesn't do anything. I don't get any error (popup are enabled), as in the screenshot. 
Only Cancel and Advanced seem to work, but forcing the import doesn't produce any change. 

<img width="603" alt="addprefix error" src="https://user-images.githubusercontent.com/8388996/83954823-e91a0980-a84c-11ea-966d-abc31ca49e0d.png">
 
I was finally able to add the vocabulary downloading the file (finding out with trial and error what the correct format is) and import it manually.  

Is the import from web disabled?

Kind regards,
-Elena

**Comment by stkenny** [comment]
Hi, it hasn't been disabled, but the number of prefixes that it works for was reduced when I removed any23 to fix dependency problems. It will only work with URLs that return RDF representations. It should return some sort of message though, so I'll look at that. I'll see if it is possible to re-introduce any23.

**Comment by stkenny** [comment]
Turns out there was an error in the javascript. Should be fixed in https://github.com/stkenny/grefine-rdf-extension/releases/download/v1.2.1-orefine-3.3/rdf-extension-1.2.1-orefine-3.3.zip. Although I'm still unable to get the DBpedia ontology to import.

**Comment by pyrog** [comment]
Same issue: I would add [Sophox](https://github.com/Sophox/sophox) OpenStreetMap prefix: see [osm2rdf/osmutils.py#L34](https://github.com/Sophox/sophox/blob/master/osm2rdf/osmutils.py#L34)
prefix | URI
--|--
osmroot|https://www.openstreetmap.org
osmnode|https://www.openstreetmap.org/node/
osmway|https://www.openstreetmap.org/way/
osmrel|https://www.openstreetmap.org/relation/
osmt|https://wiki.openstreetmap.org/wiki/Key:
osmm|https://www.openstreetmap.org/meta/

**Comment by pyrog** [comment]
Could add prefix **one by one** with Advanced… 

`osm prefix.ttl` file
```turtle
@prefix osmroot: <https://www.openstreetmap.org>.
@prefix osmnode: <https://www.openstreetmap.org/node/>.
@prefix osmway: <https://www.openstreetmap.org/way/>.
@prefix osmrel: <https://www.openstreetmap.org/relation/>.
@prefix osmm: <https://www.openstreetmap.org/meta/>.
@prefix osmt: <https://wiki.openstreetmap.org/wiki/Key:>.
```

The following step **must** be repeated for each prefix 😞 

<img width="398" alt="Add new prefix (advanced)" src="https://user-images.githubusercontent.com/2158081/89110786-74c7a500-d44e-11ea-9e01-7ce985eb50b8.png">

**Comment by stkenny** [comment]
Any23 has been added back in 1.3.0. Vocab import should work better now.
