### ISSUE TITLE
Using RDf extension with Allegrograph

### ISSUE THREAD

**Issue by stkenny** [stkenny/grefine-rdf-extension#47]
Please find below details about the issue and what has been done from our end. This is a simulated environment to recreate the issue.

We are trying to have a working integration between OpenRefine and AllegroGraph. In Allegrograph we created a repository http://3.83.135.147:10035/#/repositories/test and we uploaded the file "allegrograph_test.rdf" (From https://data.cityofnewyork.us/Public-Safety/Motor-Vehicle-Collisions-Person/f55k-p6yu). An anonymous user has been configured following https://franz.com/agraph/support/documentation/current/managing-users.html#anonymous-access.

So, we can run SPARQL queries in three ways:
 UI: http://3.83.135.147:10035/#/repositories/test/query/d/SELECT%20?s%20WHERE%20%7B%20%20%20%0A%20%20?s%20?p%20?o%20%20%0A%7D%20
API:
curl --location --request POST 'http://3.83.135.147:10035/repositories/test' \
--header 'Accept: application/json' \
--header 'Content-Type: application/x-www-form-urlencoded' \
--data-urlencode 'query=SELECT ?s WHERE {  ?s ?p ?o  }'
SPARQL endpoint:
curl --location --request POST 'http://3.83.135.147:10035/repositories/test/sparql' \
--header 'Content-Type: application/x-www-form-urlencoded' \
--data-urlencode 'query=SELECT ?s WHERE {  ?s ?p ?o  }'

OpenRefine has been configured with the "RDF extension" (https://github.com/stkenny/grefine-rdf-extension/blob/orefine/README.md). Then, we create a project in OpenRefine using a simple file "open_refine_test.csv" to reconcile the column "collision_no". Once the project has been loaded in OpenRefine we added the SPARQL Endpoint using the RDF extension:

 Click in button: RDF -> Add reconciliation service -> Based on SPARQL endpoint...
 In the new windows we added the "Name" of the service and then the "Endpoint URL": http://3.83.135.147:10035/repositories/test/sparql. Click OK
Then go to column "collision_no" action button: Reconcile -> Start reconciling...
 In the new window select the service created above and then the errors start in OpenRefine. From this, we try to add all three cases to OpenRefine with no results. In many cases, the request to Reconcile goes indefinitely and in other cases we got:
HttpException: 400 HTTP 400 error making the query: Bad Request
HttpException: -1 Unexpected error making the query: org.shaded.apache.http.impl.execchain.RequestAbortedException: Request aborted
Endpoint returned content type text/html
Internal errors in OpenRefine

We cannot find if the error is due to Allegrograph endpoint not being compatible with the OpenRefine Reconciliation service from a SPARQL endpoint or if it's something else.

**Comment by ernestorefinepro** [comment]
These are the files mentioned in the ticket description:
- [allegrograph_test.rdf](https://github.com/stkenny/grefine-rdf-extension/files/5242026/allegrograph_test.txt)
- [open_refine_test.csv](https://github.com/stkenny/grefine-rdf-extension/files/5242024/open_refine_test.txt)

Additional details:
- OpenRefine v3.3
- rdf-extension-1.2.1-orefine-3.3.zip

**Comment by stkenny** [comment]
Allegrograph seems to have its own Jena Java client, https://franz.com/agraph/support/documentation/current/java-tutorial/jena-tutorial.html, that bundles the Jena Java APIs. It's not clear to me why this is needed yet. It might mean that Allegrograph would need to be supported as a separate RDF store, similar to Virtuoso.

**Comment by stkenny** [comment]
This issue is not specific to Allegrograph. It likely would have impacted any plain SPARQL endpoint. Fixed by making sure query executor is closed.
