### ISSUE TITLE
How to reconcile using custom property?

### ISSUE THREAD

**Issue by cfragout** [stkenny/grefine-rdf-extension#51]
Hi! I'm trying to use a RDF dump of AGROVOC as a reconciliation service, but I'm unable to get any results. I've try following the documentation which can be found [here](https://github.com/stkenny/grefine-rdf-extension/wiki/Example-RDF-Dump-File-Reconciliation) but the images won't load (links are broken?).
My question is, having the following:

```
<rdf:Description rdf:about="http://aims.fao.org/aos/agrovoc/xl_en_1299487152986">
	<literalForm xmlns="http://www.w3.org/2008/05/skos-xl#" xml:lang="en">carrots</literalForm>
</rdf:Description>
```

how can I specify the full URI for the property literalForm?
Thanks!

**Comment by stkenny** [comment]
Hi, thanks for letting me know about the images. They are fixed now. The full URI would be http://www.w3.org/2008/05/skos-xl#literalForm. I was able to reconcile using that.

![Screenshot from 2020-10-24 12-13-03](https://user-images.githubusercontent.com/1716730/97080745-9bcce780-15f5-11eb-985d-f768a4a5faf2.png)
![Screenshot from 2020-10-24 12-33-56](https://user-images.githubusercontent.com/1716730/97080751-a4252280-15f5-11eb-9409-75da30c5f5ad.png)
![Screenshot from 2020-10-24 12-35-09](https://user-images.githubusercontent.com/1716730/97080755-a6877c80-15f5-11eb-9bfe-ec218c2adca8.png)

**Comment by cfragout** [comment]
It's working fine now, thanks for your help!
