### ISSUE TITLE
Slash in GREL

### ISSUE THREAD

**Issue by white-gecko** [stkenny/grefine-rdf-extension#52]
I try to create some resource URI including a slash. I currently use the GREL expression `value+"/"+cells["title"].value` but that will url-encode the `"/"`. How do I get just a slash? As I'm not very familiar with Open Refine I have attached a screenshot showing where I am within the RDF extension.

![Rastergrafik](https://user-images.githubusercontent.com/1018168/99565517-05110200-29cc-11eb-8cae-9764041b3ac7.png)

Sorry, this might be a support question and no bug, but I don't know.

**Comment by stkenny** [comment]
This does look to be an error in how the URI is being encoded. I'll need to fix that in a new release unfortunately.

**Comment by stkenny** [comment]
Actually what you could try for now is an absolute URI, so:

"http://examplemovies.org/simpsons/" + value + "/" + replace(cells["title"].value, " ", "%20")

**Comment by stkenny** [comment]
Stopped using URLEncoder which won't encode a path component properly. Should be fixed now in 1.3.0.
