### ISSUE TITLE
Problem with "reconciliation service based on RDF-file"

### ISSUE THREAD

**Issue by JennyPereira** [stkenny/grefine-rdf-extension#53]
My reconciliation service has the tags "foaf: Person", "foaf: name" and others and is loading as a service in OpenRefine. But when I start reconciliation I have no results with matches.
I don't know what to do to make it work

**Comment by stkenny** [comment]
It's difficult to say what the problem could be without more information, but when you were creating the service did you select foaf:name in the label properties?

![Screenshot from 2020-11-27 19-02-52](https://user-images.githubusercontent.com/1716730/100478477-32a02e80-30e3-11eb-98db-07ea0bcce8a4.png)

**Comment by JennyPereira** [comment]
I solved the problem. But now I have another. If my RDF file does not have any of the tags that OpenRefine provides and I have put the corresponding tag. Why am I not getting results? I am doing something wrong?
I have the tag vcard:formattedName. 
![image](https://user-images.githubusercontent.com/19669376/100527877-d1409400-31a4-11eb-8864-be045434e455.png)
These are the results:
![image](https://user-images.githubusercontent.com/19669376/100527894-fb925180-31a4-11eb-9c18-ad7d8e273acf.png)

**Comment by stkenny** [comment]
You could try the full URI http://www.w3.org/2006/vcard/ns#formattedName although http://www.w3.org/2006/vcard/ns#fn might be the correct URI.

**Comment by JennyPereira** [comment]
Thanks, it helped me.
