### ISSUE TITLE
I cannot extend my data

### ISSUE THREAD

**Issue by JennyPereira** [stkenny/grefine-rdf-extension#54]
I have selected the option "Add columns from reconciled values". But I have a "error". 
![image](https://user-images.githubusercontent.com/19669376/100945652-9e154200-34cf-11eb-96ac-160fa4b1d075.png)

I already added the service again and I have the same error. I created my service as "Based on RDF-file".

**Comment by stkenny** [comment]
Hi, the extension does not support the data extension API. If you are just looking to get the reconciled URIs then you can use 'Add column based on this column...' and then use the grel expression cell.recon.match.id to get the URI.

**Comment by JennyPereira** [comment]
So I can't extend my data with my RDF file based service? 
I want to join my CSV data with my .ttl file data

**Comment by stkenny** [comment]
Sorry I don't really follow what it is you are trying to do. It might be better to ask on the OpenRefine mailing list, as I'm not sure this is related to the RDF extension directly. Thanks.

**Comment by JennyPereira** [comment]
My service has the properties: 
`<http://gida.irekia.euskadi.eus/es/people/10484> a vcard:Individual;
vcard:formattedName "Esperanza Iñurrieta" ; 
vcard:address 
[vcard:streetAddress "Sarriena, s/n" ;vcard:postalCode "48940" ;
vcard:locality "Leioa, Bizkaia" ;
vcard:country "España" ;] ;
vcard:telephone <tel:946012231>;
vcard:tel <tel:946013311> ;
vcard:email <mailto:esperanza.inurrieta@ehu.es> ;
vcard:url <http://www.biblioteka.ehu.es> ;
vcard:title "Directora" ;
vcard:org "Biblioteca Universitaria. Universidad del País Vasco" ;.<tel:946012231> a vcard:Tel, vcard:Pref;rdf:value "946012231" ;.<tel:946013311> a vcard:Fax;rdf:value "946013311" ;.<mailto:esperanza.inurrieta@ehu.es>a vcard:Email, vcard:Pref;.`

My .csv file has the columns:
![image](https://user-images.githubusercontent.com/19669376/101099038-f7de4080-3591-11eb-9abc-6ff1c69d388a.png)

I want to extend my data. In the csv file I want to add the properties that I have in my service. But I have this error. I want to know if I made a mistake or simply the tool does not allow me to extend my data when the service was created by me.

When I reconcile my data with Wikidata I can extend, but when I do it with my own service I can't.

**Comment by stkenny** [comment]
The wikidata reconciliation supports the data extension API but the RDF
extension does not. So this won't be possible with an RDF reconciliation
service. It is not a mistake in the configuration.

**Comment by magdmartin** [comment]
@stkenny  is it possible to leave this issue open as a feature request?
