### ISSUE TITLE
Is there an API for DBpedia that allows me to reconcile?

### ISSUE THREAD

**Issue by JennyPereira** [stkenny/grefine-rdf-extension#56]
I have reconciled my data on Wikidata, but was looking for an API that I can use with DBpedia.
I found this website: https://stackoverflow.com/questions/30728563/reconciliation-services-for-openrefine-not-working, where they talk about SPARQL based reconciliation service against DBPedia. But I don't know which endpoint to load.

**Comment by stkenny** [comment]
Hi, yes, the example at https://github.com/stkenny/grefine-rdf-extension/wiki/Example-SPARQL-Endpoint-Reconciliation uses DBPedia. The endpoint is https://dbpedia.org/sparql. You should note though that the public endpoint is quite slow and I think rate limited, so if you have a large number of rows it will either take a long time or might timeout.

**Comment by JennyPereira** [comment]
oh, thank you
