### ISSUE TITLE
RDF Node with non integer cell content

### ISSUE THREAD

**Issue by gidoUninova** [stkenny/grefine-rdf-extension#61]
I was trying to create a typed literal with type xsd:double. however as soon as I select "as non-integer" nothing is added to my RDF. If I use the "as integer" option then the RDF is correctly shown. I tried also "Custom" option and it works for all primitive types such as integer, float, etc. but not with double. Example:

 foaf:age "24"^^<http://www.w3.org/2001/XMLSchema#int>;
 dbo:weight 8.0E1;

It should be:

 dbo:weight "8.0E1"^^<http://www.w3.org/2001/XMLSchema#double>;

**Comment by stkenny** [comment]
Fixed in https://github.com/stkenny/grefine-rdf-extension/releases/download/v1.3.1/rdf-extension-1.3.1.zip
