### ISSUE TITLE
Installation RDF extension - wrong home screen on OpenRefine

### ISSUE THREAD

**Issue by MarcoAartsen** [stkenny/grefine-rdf-extension#62]
Dear all,

I have some difficulties with the installation of the RDF extension. I just downloaded the OpenRefine v1.3.1. extension zipfile from the stkenny / grefine-extensions repository (screenshot 1). Next, I unpacked the zip file and dragged the content to the correct directory: `C:\Users\marco\AppData\Local\OpenRefine\extensions\rdf-extensions` (screenshot 2 & 3). 

After this, I restarted OpenRefine and the home screen doesn't seems correct (screenshot 4). I only see 'open project' and 'create project' on the left side, but when opening a existing project I see a bug (screenshot 5). The 'import project' and 'language settings' features are lost. 

I also have the latest version of Java (version 8), so if anyone can help me out, I really do appreciate this.

Kind regards, 
Marco Aartsen
 
![Latest_release_OpenRefine_v1 3 1_screenshot 1](https://user-images.githubusercontent.com/88377058/134173909-913e17e5-e2e4-444f-a1d9-76dbf66bda9a.PNG)
![OpenRefine_Directory_screenshot 2](https://user-images.githubusercontent.com/88377058/134173918-c43d5213-6007-4cb7-90f2-d3df4d416cca.png)
![OpenRefine_Directory_screenshot 3](https://user-images.githubusercontent.com/88377058/134173921-d909a2b2-b9c8-4385-ad04-7667d9f7f73c.png)
![OpenRefine_BlueScreen_screenshot 4](https://user-images.githubusercontent.com/88377058/134173910-98703bfe-e8b4-4eb6-b965-17ca29a13e5e.PNG)
![OpenRefine_Bug_HomeScreen_screenshot 5](https://user-images.githubusercontent.com/88377058/134173915-6bf22062-d636-4f5a-8952-087d3f48c9e1.PNG)

**Comment by stkenny** [comment]
Hi, sorry I haven't been able to reproduce this error. I tried with both OpenRefine 3.4.1 and 3.5 beta1 on Mac. Can you say what OpenRefine version you have and what browser you are using. I tried both Chrome and Firefox and both appeared correct.

**Comment by MarcoAartsen** [comment]
Hi, I use chrome as a browser and OpenRefine 3.4.1. Would you like to receive a screenshot of the command-line scripts, maybe this will give some extra feedback?

**Comment by stkenny** [comment]
HI, yes, if you can, that might help. Thanks.

**Comment by MarcoAartsen** [comment]
Here you go:
![Screendump_command-line_scripts_OpenRefine](https://user-images.githubusercontent.com/88377058/134213653-c04c0585-adf0-4f51-87a0-20e14e43c583.PNG)

**Comment by MarcoAartsen** [comment]
Hi, I managed to solve the bug. However, when creating a new project, I receive an error when closing and opening OpenRefine. This is what the command-line says:

`17:19:38.379 [            refine_server] Starting Server bound to '127.0.0.1:3333' (0ms)
17:19:38.396 [            refine_server] Initializing context: '/' from 'C:\Users\marco\Desktop\CaseStudy_PowerHouse_LOD\openrefine-3.4.1\webapp' (17ms)
SLF4J: Class path contains multiple SLF4J bindings.
SLF4J: Found binding in [jar:file:/C:/Users/marco/Desktop/CaseStudy_PowerHouse_LOD/openrefine-3.4.1/server/target/lib/slf4j-log4j12-1.7.18.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: Found binding in [jar:file:/C:/Users/marco/Desktop/CaseStudy_PowerHouse_LOD/openrefine-3.4.1/webapp/WEB-INF/lib/slf4j-log4j12-1.7.18.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: See http://www.slf4j.org/codes.html#multiple_bindings for an explanation.
SLF4J: Actual binding is of type [org.slf4j.impl.Log4jLoggerFactory]
17:19:39.329 [                   refine] Starting OpenRefine 3.4.1 [437dc4d]... (933ms)
17:19:39.329 [                   refine] initializing FileProjectManager with dir (0ms)
17:19:39.329 [                   refine] C:\Users\marco\AppData\Local\OpenRefine (0ms)
**17:19:39.513 [       FileProjectManager] Failed to recover project in directory 1987537154093.project (184ms)**
17:19:46.252 [                   refine] POST /command/core/load-language (6739ms)
17:19:46.294 [                   refine] GET /command/core/get-preference (42ms)
17:19:46.317 [                   refine] POST /command/core/load-language (23ms)
17:19:46.323 [                   refine] POST /command/core/load-language (6ms)
17:19:46.509 [                   refine] POST /command/core/get-importing-configuration (186ms)
17:19:46.550 [                   refine] GET /command/core/get-all-project-tags (41ms)
17:19:46.580 [                   refine] GET /command/core/get-all-project-metadata (30ms)
17:19:46.667 [                   refine] GET /command/core/get-csrf-token (87ms)
17:19:46.687 [                   refine] GET /command/core/get-languages (20ms)
17:19:46.728 [                   refine] GET /command/core/get-version (41ms)
17:19:47.022 [                   refine] GET /command/database/saved-connection (294ms)
`
Any idea how to solve this, because I can't save newly created projects right now.

Kind regards,
Marco

**Comment by MarcoAartsen** [comment]
Hi, I am sorry, my latest error message has no relation to the RDF extension. I was trying to say that I solved the RDF-related bug on my own. Then, I introduced a new issue about the recovery of existing projects, when opening OpenRefine. Maybe I should close this thread and open a new one?

**Comment by stkenny** [comment]
Hi, yes if this is a new problem then it would be best in the OpenRefine github or mailing list. It would be helpful to know what the original problem was?

**Comment by MarcoAartsen** [comment]
Okay, then I will close this thread. In reaction to your second sentence: the original problem is clear, in my opinion (see screenshots). Do you mean that it would be helpful to tell what the solution to the problem was?

**Comment by stkenny** [comment]
Unclear if the original issue is related to the RDF extension or not. Unable to reproduce.
