### ISSUE TITLE
Apache subdomain and ProxyPass to 127.0.0.1 url issue reconciliation

### ISSUE THREAD

**Issue by ralcazar-oeg** [stkenny/grefine-rdf-extension#9]
Hello. I opened an Issue about this in openrefine and they redirected me here. 
https://github.com/OpenRefine/OpenRefine/issues/1766

I'm running a open refine instance in a subdomain like http://refine.domain.com/ and it works like a charm. ubuntu server 16.04 with apache and a ProxyPass from the subdomain to http://127.0.0.1:3358

no_proxy="localhost,127.0.0.1"
REFINE_PORT=3358
#REFINE_HOST=127.0.0.1
#REFINE_WEBAPP=main\webapp

It's accessed from our internal network and other external network, so multiple students can access and share it in the same instance.

Permalink points correctly to our subdomain http://refine.domain.com/project?project=213154...etc and is accessed fine

**The problem occurs when we reconciliate csv data with dbpedia.** It works perfect, but the url changes. Records (borough) points to http://127.0.0.1:3358/extension/rdf-extension/services/dbpedia/view?id=http://dbpedia.org/resource/The_Bronx

instead of
http://refine.domain.com/extension/rdf-extension/services/dbpedia/view?id=http://dbpedia.org/resource/The_Bronx (this url forward it to http://dbpedia.org/page/The_Bronx)

I'm not sure if the solution has to be applied in the apache proxy or If I should hardcode the subdomain name in openrefine with a parameter

Any help with this will be appreciated. Thanks.

**Comment by stkenny** [comment]
Hi, did you add the service before putting OpenRefine behind the proxy? I just tried adding a service while OpenRefine was running behind an apache proxy and it seems to return the correct URLs. So maybe re-add the service as a workaround for now?

**Comment by ralcazar-oeg** [comment]
Hello. I'll try to remove and add again the RDF extension and will notify you if this solves the issue.
Thank you for the answer.
